In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
data = pd.read_csv('clean_data.csv')

In [3]:
data.head(5)

Unnamed: 0     budget                                             genres  \
0           0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1           1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2           2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3           3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4           4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

       id                                           keywords  \
0   19995  [{"id": 1463, "name": "culture clash"}, {"id":...   
1     285  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  206647  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3   49026  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4   49529  [{"id": 818, "name": "based on novel"}, {"id":...   

  original_language                            original_title  \
0                en                                    Avatar   
1                en  Pirates of the Caribbean: At World's End   
2                en                                   Spectre   
3                en                     The Dark Knight Rises   
4                en                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies release_date     revenue  \
0  [{"name": "Ingenious Film Partners", "id": 289...   2009-12-10  2787965087   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   2007-05-19   961000000   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   2015-10-26   880674609   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   2012-07-16  1084939099   
4        [{"name": "Walt Disney Pictures", "id": 2}]   2012-03-07   284139100   

   runtime                                   spoken_languages  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...   
1    169.0           [{"iso_639_1": "en", "name": "English"}]   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...   
3    165.0           [{"iso_639_1": "en", "name": "English"}]   
4    132.0           [{"iso_639_1": "en", "name": "English"}]   

                                          tagline  vote_average  vote_count  \
0                     Enter the World of Pandora.           7.2       11800   
1  At the end of the world, the adventure begins.           6.9        4500   
2                           A Plan No One Escapes           6.3        4466   
3                                 The Legend Ends           7.6        9106   
4            Lost in our world, found in another.           6.1        2124   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [4]:
data.shape

(4803, 19)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Unnamed: 0            4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4803 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  release_date          4802 non-null   object 
 11  revenue               4803 non-null   int64  
 12  runtime               4801 non-null   float64
 13  spoken_languages      4803 non-null   object 
 14  tagline               3959 non-null   object 
 15  vote_average         

In [6]:
data.dtypes

Unnamed: 0                int64
budget                    int64
genres                   object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
tagline                  object
vote_average            float64
vote_count                int64
cast                     object
crew                     object
dtype: object

In [7]:
data['overview']

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...                        
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: overview, Length: 4803, dtype: object

In [8]:
data['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [9]:
data['overview'].isnull().sum()

3

In [10]:
data['overview'] = data['overview'].fillna('')

In [12]:
data['overview'].isnull().sum()

0

We need to convert this text to vector using NLP.

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [18]:
tfv = TfidfVectorizer(min_df=3, max_features=None, ngram_range=(1,3), stop_words='english')

In [19]:
tfv_matrix = tfv.fit_transform(data['overview'])

In [20]:
tfv_matrix

<4803x9919 sparse matrix of type '<class 'numpy.float64'>'
	with 121480 stored elements in Compressed Sparse Row format>

In [21]:
tfv_matrix.shape

(4803, 9919)

In [22]:
data['overview'].shape

(4803,)

In [23]:
data['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [26]:
tfv_matrix[0].T.toarray()

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [28]:
X = tfv_matrix.toarray()

In [30]:
df2 = pd.DataFrame(X)

In [31]:
df2

0     1     2     3     4     5     6     7     8     9     ...  9909  \
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
4798   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4799   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4800   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4801   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4802   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      9910  9911  9912  9913  9914  9915  9916  9917  9918  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
4798   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4799   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4800   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4801   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4802   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[4803 rows x 9919 columns]

In [32]:
from sklearn.metrics.pairwise import sigmoid_kernel

In [33]:
sig = sigmoid_kernel(tfv_matrix, tfv_matrix)

In [35]:
sig[0]

array([0.76163649, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
       0.76159416])

In [37]:
index = data.index

In [38]:
index[4802]

4802

In [40]:
title = data['original_title']

In [41]:
title[4802]

'My Date with Drew'

In [44]:
indices = pd.Series(data.index, index=data['original_title'])

In [45]:
indices

original_title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ... 
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

In [65]:
indices['Avatar'] 

0

In [66]:
sig[4799]

array([0.76159416, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
       0.76159416])

In [67]:
sig[indices['Avatar']]

array([0.76163649, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
       0.76159416])

In [68]:
list(sig[indices['Avatar']])

[0.7616364930962501,
 0.7615941559557649,
 0.7615941559557649,
 0.761595125164868,
 0.7615941559557649,
 0.761595309447695,
 0.7615941559557649,
 0.761595908255829,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615950846887262,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.76159572705,
 0.7615962614863476,
 0.7615941559557649,
 0.7615952950243241,
 0.7615941559557649,
 0.7615968611459101,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.761597988130195,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615941559557649,
 0.7615951605621958,
 0.7615941559557649,
 0.7615968356260668,
 0.7615941559557649,
 0.7615956092492897,
 

In [69]:
list(enumerate(list(sig[indices['Avatar']])))

[(0, 0.7616364930962501),
 (1, 0.7615941559557649),
 (2, 0.7615941559557649),
 (3, 0.761595125164868),
 (4, 0.7615941559557649),
 (5, 0.761595309447695),
 (6, 0.7615941559557649),
 (7, 0.761595908255829),
 (8, 0.7615941559557649),
 (9, 0.7615941559557649),
 (10, 0.7615941559557649),
 (11, 0.7615950846887262),
 (12, 0.7615941559557649),
 (13, 0.7615941559557649),
 (14, 0.7615941559557649),
 (15, 0.7615941559557649),
 (16, 0.7615941559557649),
 (17, 0.7615941559557649),
 (18, 0.7615941559557649),
 (19, 0.7615941559557649),
 (20, 0.7615941559557649),
 (21, 0.7615941559557649),
 (22, 0.7615941559557649),
 (23, 0.7615941559557649),
 (24, 0.7615941559557649),
 (25, 0.7615941559557649),
 (26, 0.76159572705),
 (27, 0.7615962614863476),
 (28, 0.7615941559557649),
 (29, 0.7615952950243241),
 (30, 0.7615941559557649),
 (31, 0.7615968611459101),
 (32, 0.7615941559557649),
 (33, 0.7615941559557649),
 (34, 0.7615941559557649),
 (35, 0.7615941559557649),
 (36, 0.761597988130195),
 (37, 0.761594155955

In [70]:
sigma_scores = sorted(list(enumerate(list(sig[indices['Avatar']]))), key=lambda x:x[1], reverse=True)

In [71]:
sigma_scores

[(0, 0.7616364930962501),
 (1341, 0.7616030155858681),
 (634, 0.7616028561141562),
 (3604, 0.761601930611584),
 (2130, 0.7616015339622925),
 (775, 0.7616011086528327),
 (529, 0.7615996114069044),
 (151, 0.7615991171152051),
 (311, 0.7615990624497703),
 (847, 0.7615987706430225),
 (570, 0.7615986450599548),
 (942, 0.7615984376900236),
 (36, 0.761597988130195),
 (1610, 0.7615979793934843),
 (3070, 0.7615978406764746),
 (1033, 0.7615978182403835),
 (2628, 0.7615977834088159),
 (1784, 0.7615977150705628),
 (2578, 0.7615976778191441),
 (150, 0.7615976453752453),
 (3724, 0.7615975951237102),
 (1013, 0.761597590729192),
 (4211, 0.7615975631290406),
 (1213, 0.7615975380289366),
 (1345, 0.7615974549075267),
 (312, 0.7615974086679764),
 (4039, 0.7615973645677722),
 (2967, 0.7615973512232982),
 (614, 0.7615972949789032),
 (281, 0.7615972537743877),
 (174, 0.7615972462403858),
 (3493, 0.7615971922075142),
 (3624, 0.7615971821325882),
 (972, 0.7615971791001622),
 (1274, 0.7615971587672579),
 (1959,

In [72]:
sigma_scores[1:11] #Top 10 movies

[(1341, 0.7616030155858681),
 (634, 0.7616028561141562),
 (3604, 0.761601930611584),
 (2130, 0.7616015339622925),
 (775, 0.7616011086528327),
 (529, 0.7615996114069044),
 (151, 0.7615991171152051),
 (311, 0.7615990624497703),
 (847, 0.7615987706430225),
 (570, 0.7615986450599548)]

In [73]:
ind = [index[0] for index in sigma_scores[1:11]]

In [74]:
ind

[1341, 634, 3604, 2130, 775, 529, 151, 311, 847, 570]

In [75]:
data['original_title'].iloc[ind]

1341                Obitaemyy Ostrov
634                       The Matrix
3604                       Apollo 18
2130                    The American
775                        Supernova
529                 Tears of the Sun
151                          Beowulf
311     The Adventures of Pluto Nash
847                         Semi-Pro
570                           Ransom
Name: original_title, dtype: object

In [80]:
def give_recommendation(title, model):
    idx = indices[title]
    model_scores = list(enumerate(list(model[indices[idx]])))
    
    model_scores = sorted(model_scores, key=lambda x:x[1], reverse=True)
    
    model_scores = model_scores[1:11]
    
    movie_indices = [index[0] for index in model_scores]
    
    return data['original_title'].iloc[movie_indices]

In [81]:
give_recommendation('Avatar', sig)

1341                Obitaemyy Ostrov
634                       The Matrix
3604                       Apollo 18
2130                    The American
775                        Supernova
529                 Tears of the Sun
151                          Beowulf
311     The Adventures of Pluto Nash
847                         Semi-Pro
570                           Ransom
Name: original_title, dtype: object